@serviceresource =  catalogue/categories

###
// @name info
GET {{devProxyBaseUrl}}/{{service}}/info HTTP/1.1
###

###
// @name create_category
POST {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title":"jarius",
  "parentId":"60a4161968d5f47f0ccc03fe"
}
###

###
// @name list_categories
GET {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
###

###
// @name get_category
GET {{devProxyBaseUrl}}/{{serviceresource}}/609f929901d9974e19d489b9 HTTP/1.1
Authorization: Bearer {{token}}
###

###
// @name edit_category
PUT {{devProxyBaseUrl}}/{{serviceresource}}/60a4164668d5f47f0ccc0400 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title":"Jarius joushua"
}
###

###
// @name edit_category_sibling
PUT {{devProxyBaseUrl}}/{{serviceresource}}/60a4161968d5f47f0ccc03fe/siblingorder HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siblingOrder":["60a4164668d5f47f0ccc0400","60a4164068d5f47f0ccc03ff"]
}
###


###
// @name edit_category_position
PUT {{devProxyBaseUrl}}/{{serviceresource}}/609f876fd346b53a4019b3e9/position HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldParentId": "609edad00da307320e18d7e9",
  "newParentId": "609f927501d9974e19d489b8"
}
###

###
// @name delete_category
DELETE  {{devProxyBaseUrl}}/{{serviceresource}}/60a415fe68d5f47f0ccc03fb HTTP/1.1
Authorization: Bearer {{token}}
###