@serviceresource =  catalogue/products


###
// @name create_product
POST {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"Cake1",
  "barcode":"123456789",
  "description":"A wonderful Cake",
  "brand":"60bbef3ef8e1c1aeacbd2784",
  "category":"60c52e0505f7ea45c9ea08c7"
}
###
