@serviceresource =  catalogue/brands
@brandId = 60d7500584cf99f3b5df7005


###
// @name create_brand
POST {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"RohitRaj3"
}
###


###
// @name get_brands
GET {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
###


###
// @name get_brand
GET {{devProxyBaseUrl}}/{{serviceresource}}/{{brandId}} HTTP/1.1
Authorization: Bearer {{token}}
###

###
// @name edit_brand
PUT {{devProxyBaseUrl}}/{{serviceresource}}/{{brandId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"noelimmi"
}
###


###
// @name delete_brand
DELETE {{devProxyBaseUrl}}/{{serviceresource}}/{{brandId}} HTTP/1.1
Authorization: Bearer {{token}}
###
