@serviceresource =  catalogue/taxbrackets


###
// @name create_taxbracket
POST {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"SGST",
  "rate":10.43
}
###

###
// @name create_taxgroup
POST {{devProxyBaseUrl}}/{{serviceresource}}/groups HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name":"GST+SGST4",
  "bracket":["60c8fecaa7b7c286a43d8713","60c8fee3a7b7c286a43d8714"]
}
###

###
// @name get_all_taxbrackets
GET {{devProxyBaseUrl}}/{{serviceresource}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
###
